src/CoreSys/AdBundle/Entity/Advertiser.php
<?php

namespace CoreSys\AdBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use CoreSys\AdvertiserBundle\Entity\Advertiser as BaseEntity;
use CoreSys\AdBundle\Entity\Campaign;

/**
 * Advertiser
 *
 * @ORM\Table(name="ad_advertiser")
 * @ORM\Entity(repositoryClass="CoreSys\AdBundle\Entity\AdvertiserRepository")
 * @ORM\HasLifecycleCallbacks
 */
class Advertiser extends BaseEntity
{
    /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="CoreSys\AdBundle\Entity\Campaign", mappedBy="advertiser")
     */
    private $campaigns;
    /**
     * @var bool
     *
     * @ORM\Column(name="active", type="boolean", nullable=true)
     */
    private $active;

    /**
     *
     */
    public function __construct()
    {
        parent::__construct();
        $this->setCampaigns(new ArrayCollection());
        $this->setActive(true);
    }

    /**
     * Get campaigns
     *
     * @return ArrayCollection
     */
    public function getCampaigns()
    {
        return $this->campaigns;
    }

    /**
     * Set campaigns
     *
     * @param ArrayCollection $campaigns
     * @return Advertiser
     */
    public function setCampaigns($campaigns)
    {
        $this->campaigns = $campaigns;

        return $this;
    }

    /**
     * @param Campaign $campaign
     * @return $this
     */
    public function addCampaign(Campaign $campaign)
    {
        if (!$this->campaigns->contains($campaign)) {
            $this->campaigns->add($campaign);
        }
        return $this;
    }

    /**
     * @param Campaign $campaign
     * @return $this
     */
    public function removeCampaign(Campaign $campaign)
    {
        if ($this->campaigns->contains($campaign)) {
            $this->campaigns->removeElement($campaign);
        }
        return $this;
    }

    public function getAdminTableArray()
    {
        $user_data = $this->getUser()->getAdminTableArray();
        $data = array();
        $data['user'] = $user_data;

        $data['id'] = $this->getId();
        $data['campaigns'] = 0;
        $data['campaigns_count'] = 0;
        $data['ads_count'] = 0;
        $data['ads'] = 0;
        $data['active'] = $data['enabled'] = $this->getActive();
        $data['check'] = '<input type="checkbox" value="' . $this->getId() . '" data-id="' . $this->getId() . '" class="row-check" />';

        return $data;
    }

    public function getActive()
    {
        if (empty($this->active)) {
            $this->active = true;
        }
        return $this->active === true;
    }

    public function setActive($active = true)
    {
        $this->active = $active === true;
        return $this;
    }

    public function getCampaignsCount()
    {
        return count($this->campaigns);
    }
}

src/CoreSys/AdBundle/Controller/AdminAdvertisersController.php
<?php

namespace CoreSys\AdBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use CoreSys\SiteBundle\Controller\AdminController as BaseController;

/**
 * Class AdminAdvertisersController
 * @package CoreSys\AdBundle\Controller
 * @Route("/admin/ads/advertisers")
 */
class AdminAdvertisersController extends BaseController
{
    /**
     * @Route("/", name="admin_ads_advertisers_index", defaults={"slug"=null})
     * @Route("/{slug}", name="admin_ads_advertisers_slug", defaults={"slug"=null})
     * @Template()
     */
    public function indexAction( $slug )
    {
        if( !empty( $slug ) ) {
            return $this->redirect( $this->generateUrl( 'admin_ads_advertisers_manage', array( 'slug' => $slug ) ) );
        }
        return array();
    }

    /**
     * @Route("/manage/{slug}", name="admin_ads_advertisers_manage", defaults={"slug"=null}, options={"expose"=true})
     * @Template()
     */
    public function manageAction( $slug )
    {
        $repo = $this->getRepo( 'CoreSysAdBundle:Advertiser' );
        $advertiser = $repo->locateAdvertiser( $slug );

        if( empty( $advertiser ) ) {
            $this->msgError( 'Could not locate advertiser' );
            return $this->redirect( $this->generateUrl( 'admin_ads_advertisers_index' ) );
        }

        return array( 'advertiser' => $advertiser );
    }
}

src/CoreSys/AdBundle/Resources/views/AdminAdvertisers/index.html.twig
{% extends 'CoreSysThemeBundle::admin.html.twig' %}

{% block head_title %}
    Advertisers Management
{% endblock head_title %}

{% block page_title %}
    Advertisers Management
    <small>View/Add/Edit/Remove Advertisers</small>
    <div class="pull-right">
        <div id="sparkline-bar" class="graph sparkline hidden-xs" style="margin-right:25px;"></div>
    </div>
{% endblock page_title %}

{% block page_breadcrumbs %}
    <li>
        <a href="{{ path( 'admin_ads_advertisers_index' ) }}">Advertisers Management</a>
        <i class="fa fa-angle-right"></i>
    </li>
{% endblock page_breadcrumbs %}

{% block head_page_level_css %}
    {{ parent() }}
    <link rel="stylesheet" type="text/css" href="{{ plugin_asset( 'select2/select2_metro.css' ) }}"/>
    <link rel="stylesheet" type="text/css" href="{{ plugin_asset( 'bootstrap-colorpicker/css/colorpicker.css' ) }}"/>
    {% include 'CoreSysThemeBundle:Metronic:admin_datatables_includes_css.html.twig' %}
    {% include 'CoreSysThemeBundle:Metronic:typeahead_css.html.twig' %}

{% endblock head_page_level_css %}

{% block page_level_js %}
    {{ parent() }}
    <script type="text/javascript" src="{{ plugin_asset( 'select2/select2.min.js' ) }}"></script>
    {% include 'CoreSysThemeBundle:Metronic:admin_datatables_includes_js.html.twig' %}
    <script type="text/javascript"
            src="{{ plugin_asset( 'bootstrap-colorpicker/js/bootstrap-colorpicker.js' ) }}"></script>
    <script type="text/javascript" src="{{ plugin_asset( 'jquery.form.min.js' ) }}"></script>
    {% include 'CoreSysThemeBundle:Metronic:typeahead_javascript.html.twig' %}
{% endblock page_level_js %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="portlet">
                <div class="portlet-title">
                    <div class="caption">
                        Advertiser Management
                    </div>
                    <div class="actions">
                        <a class="btn btn-primary btn-sm add-advertiser" href="javascript:void(0)"><i
                                    class="fa fa-plus-circle"></i> Add Advertiser</a>
                        <a class="btn btn-danger display-hide btn-sm remove-advertisers" href="javascript:void(0)"><i
                                    class="fa fa-times-circle"></i> Remove
                            <span class="selected-count">0</span> Advertiser(s)</a>
                    </div>
                </div>
                <div class="portlet-body">
                    <table id="advertisers-table" class="table table-striped table-bordered table-hover">
                        <thead>
                        <tr>
                            <th data-hide="phone,tablet" width="20"><input type="checkbox" class="master-check"/></th>
                            <th data-hide="phone,tablet">ID</th>
                            <th data-class="expand">Advertiser</th>
                            <th data-hide="phone">Email</th>
                            <th data-hide="always,phone,tablet">Created</th>
                            <th data-hide="always,phone,tablet">Last Login</th>
                            <th data-hide="phone">Roles</th>
                            <th data-hide="always,phone,tablet">Campaigns</th>
                            <th data-hide="always,phone,tablet">Ads</th>
                            <th data-hide="always,phone,tablet">Status</th>
                            <th data-hide="phone,tablet" width="150">Options</th>
                        </tr>
                        </thead>
                        <tbody>

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="new-modal" tabindex="-1" access="dialog" aria-labelledby="new-modal"
         aria-hidden="true"></div>
    <div class="modal fade" id="edit-modal" tabindex="-1" access="dialog" aria-labelledby="edit-modal"
         aria-hidden="true"></div>
    <div class="modal fade" id="view-modal" tabindex="-1" access="dialog" aria-labelledby="view-modal"
         aria-hidden="true"></div>
{% endblock content %}

{% block body_js %}
    <script type="application/javascript"
            src="{{ plugin_asset( 'CoreSys/js/jquery.adminAjaxTablePage.js' ) }}"></script>
    <script type="application/javascript"
            src="{{ asset( 'bundles/coresysad/js/jquery.adminAdvertiserPage.js') }}"></script>
    <script type="application/javascript">
        var page;
        $(document).ready(function () {
            page = new $.fn.adminAdvertiserPage();
            page = page.page;
        });
    </script>
{% endblock body_js %}

src/CoreSys/AdBundle/Resources/views/AdminAdvertisers/manage.html.twig
{% extends 'CoreSysThemeBundle::admin.html.twig' %}

{% block head_title %}
    Advertiser {{ advertiser.user.username }}
{% endblock head_title %}

{% block page_title %}
    Advertiser {{ advertiser.user.username }}
    <small>Manage/View Advertiser</small>
{% endblock page_title %}

{% block page_breadcrumbs %}
    <li>
        <a href="{{ path( 'admin_ads_advertisers_index' ) }}">Advertisers Management</a>
        <i class="fa fa-angle-right"></i>
    </li>
    <li>
        <a href="{{ path( 'admin_ads_advertisers_manage', {'slug': advertiser.user.username} ) }}">Advertiser {{ advertiser.user.username }}</a>
    </li>
{% endblock page_breadcrumbs %}

{% block head_page_level_css %}
    {{ parent() }}
    <link type="text/css" rel="stylesheet" href="{{ admin_theme_asset( 'css/pages/profile.css') }}"/>
{% endblock head_page_level_css %}

{% block page_level_js %}
    {{ parent() }}
    <script type="text/javascript" src="{{ plugin_asset( 'jquery.form.min.js' ) }}"></script>
{% endblock page_level_js %}

{% block content %}
    <div class="row profile">
        <div class="col-md-12">
            <div class="portlet">
                <div class="portlet-title">
                    <div class="caption">
                        Advertiser {{ advertiser.user.username }}
                    </div>
                    <div class="actions">
                        <a class="btn btn-primary btn-sm edit-advertiser" href="javascript:void(0)"><i class="fa fa-edit"></i> Edit Advertiser</a>
                    </div>
                </div>
                <div class="portlet-body">
                    {% include 'CoreSysAdBundle:AdminAdvertisers:manage_tabs.html.twig' %}
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="new-modal" tabindex="-1" access="dialog" aria-labelledby="new-modal" aria-hidden="true"></div>
    <div class="modal fade" id="edit-modal" tabindex="-1" access="dialog" aria-labelledby="edit-modal" aria-hidden="true"></div>
    <div class="modal fade" id="view-modal" tabindex="-1" access="dialog" aria-labelledby="view-modal" aria-hidden="true"></div>
{% endblock content %}

{% block body_js %}

{% endblock body_js %}

src/CoreSys/AdBundle/Resources/views/AdminAdvertisers/manage_tab_account.html.twig
<div class="tab-pane" id="account">
    Account
</div>

src/CoreSys/AdBundle/Resources/views/AdminAdvertisers/manage_tab_campaigns.html.twig
<div class="tab-pane" id="campaigns">
    Campaigns
</div>

src/CoreSys/AdBundle/Resources/views/AdminAdvertisers/manage_tabs.html.twig
<div class="tabbable tabbable-custom tabbable-full-width">
    <ul class="nav nav-tabs ">
        <li class="active"><a href="#overview" data-toggle="tab">Overview</a></li>
        <li class=""><a href="#campaigns" class="campaigns_tab" data-toggle="tab">Campaigns <span class="campaigns_count">{{ advertiser.campaignsCount }}</span></a></li>
        <li class=""><a href="#account" class="account_tab" data-toggle="tab">Account</a></li>
    </ul>
    <div class="tab-content">
        {% include 'CoreSysAdBundle:AdminAdvertisers:manage_tab_overview.html.twig' %}
        {% include 'CoreSysAdBundle:AdminAdvertisers:manage_tab_campaigns.html.twig' %}
        {% include 'CoreSysAdBundle:AdminAdvertisers:manage_tab_account.html.twig' %}
    </div>
</div>